version = 0.1
[default.deploy.parameters]
stack_name = "java-spring-app"
resolve_s3 = true
s3_prefix = "java-spring-app"
region = "us-east-1"
profile = "my-aws-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
